### PR TITLE
disable CoreDNS in client mode or if port 53 is in use

### LINKED ISSUE #62: Unclear how to disable CoreDNS
## Expected Behavior

When in client mode, the CoreDNS instance may not be necessary, or even obstructive, e.g. when using `--network host`. The latter might be necessary when using IPv6.

## Current Behavior

Starting the container in host networking mode works fine, and IPv6 also works as expected. However the container starts a CoreDNS instance on port 53, which – in this networking mode – is the host port. 

In the most cases when run as client, it is not necessary to run a DNS server. As it uses port 53, there might even be conflicts with other services on the host.

## Steps to Reproduce
1. Use the container in client mode with `--network host`

## Environment
**OS:** Linuxx
**CPU architecture:** arm32
**How docker service was installed:** Debian docker.io packages

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

… where `./config/wg0.conf` is an existing and working WireGuard client configuration.

### PR DESCRIPTION
**Pull request by aptalca**
closes #62

### CODE REVIEW

**Review by drizuid — APPROVED** [review]

File: root/etc/services.d/coredns/run [hunk 1]
```diff
@@ -2,5 +2,10 @@
 
 cd /config/coredns
 
-exec \
-    /app/coredns -dns.port=53
\ No newline at end of file
+if netstat -apn | grep -q ":53 "; then
```
Comment (fermulator) [inline root/etc/services.d/coredns/run:5]: lgtm: :+1: - this addresses the use case of server mode & docker host networking if pihole is already hogging the port :)
